name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        shell: powershell
        run: |
          az login --service-principal `
            --username 033c042d-e6cc-4399-91cf-b93b7bd5dcba
            --password yrV8Q~1ANlabpp-KGcK2C2aqhRx3YGm3XUxwHbxq
            --tenant 4611c619-c77c-404a-b26f-b286f3681168

      - name: Debug Workspace
        shell: powershell
        run: |
          Write-Host "Current Location:"
          Get-Location

          Write-Host "Files in Workspace:"
          Get-ChildItem -Force

          Write-Host "Terraform Files:"
          Get-ChildItem -Recurse -Filter *.tf

      - name: Show main.tf
        shell: powershell
        run: |
          Write-Host "===== main.tf ====="
          Get-Content .\main.tf

      - name: Terraform Version
        shell: powershell
        run: terraform version

      - name: Terraform Init
        shell: powershell
        run: terraform init

      - name: Terraform Validate
        shell: powershell
        run: terraform validate

      - name: Terraform Plan
        shell: powershell
        run: terraform plan

      - name: Terraform Apply
        shell: powershell
        run: terraform apply -auto-approve
