name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        run: |
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Debug Workspace
        run: |
          Get-Location
          Get-ChildItem -Force
          Get-ChildItem -Recurse -Filter *.tf

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
