name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        run: |
          az login --service-principal --username 033c042d-e6cc-4399-91cf-b93b7bd5dcba --password yrV8Q~1ANlabpp-KGcK2C2aqhRx3YGm3XUxwHbxq --tenant 4611c619-c77c-404a-b26f-b286f3681168

      - name: Debug Workspace
        run: |
          Get-Location
          Get-ChildItem -Force
          Get-ChildItem -Recurse -Filter *.tf
          - name: Show Terraform Files
            run: |
              Write-Host "===== main.tf ====="
              Get-Content main.tf

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
