name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: azure login
        run: az login az login --service-pricipal --username 033c042d-e6cc-4399-91cf-b93b7bd5dcba --password yrV8Q~1ANlabpp-KGcK2C2aqhRx3YGm3XUxwHbxq
      - name: Terraform init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform plan
        run: terraform plan
      - name: Terraform apply
        run: terraform apply -auto-approve
        
