name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v4

      - name: CMD Test
        shell: cmd
        run: |
          echo Hello World
          echo Second Line
